spring:
  application:
    name: config-dev-file

# eureka Client Configurations
eureka: 
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
# Actuator Configurations  
management:
  endpoints:
    web:
      exposure:
        include: "*"     # Expose all endpoints
  endpoint:
    health:
      show-details: always     # Show full health details
